import { Inter } from "next/font/google";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

import Link from 'next/link';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <Link href={'/about'}>about</Link>
        </div>
        <div>
          <Link href={'/resume'}>resume</Link>
        </div>
        <div>
          <Link href={'/chart'}>chart</Link>
        </div>
        <div>
          <Link href={'/free'}>free</Link>
        </div>
        <div>
          <Link href={'/contact'}>Contact</Link>
        </div>
      </main>
    </>
  );
}
